name: Backend Tests

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Verify package-lock.json
        working-directory: ./backend
        run: |
          if [ ! -f "package-lock.json" ]; then
            echo "package-lock.json not found. Running npm install to generate it..."
            npm install
          fi

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Run tests
        working-directory: ./backend
        run: npm test
        env:
          NODE_ENV: test
