name: Backend Tests

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        working-directory: ./backend
        run: npm ci
        env:
          NODE_ENV: test
      - name: Run tests
        working-directory: ./backend
        run: cd backend && npm test
        env:
          NODE_ENV: test
